### ISSUE TITLE
MVVM, Riverpod state management and Folder by feature structure

### ISSUE THREAD

**Issue by dinurymomshad** [KalleHallden/exer_log#10]
Hey big fan of your videos. 
Honestly, I have been waiting for this. So let's get to work.

I went through the code base.  I'd like to propose organising the directory as following for the new comers to adapt easily:

<img width="615" alt="Screenshot 2022-08-05 at 11 26 02 PM" src="https://user-images.githubusercontent.com/26508767/183129506-b908d84e-57ff-4c56-a05a-a3e61b882f81.png">

**Comment by dinurymomshad** [comment]
Ideally inside authentication directory this is what I normally do:

<img width="604" alt="Screenshot 2022-08-05 at 11 29 44 PM" src="https://user-images.githubusercontent.com/26508767/183130034-2f8b8ab9-109f-4d4b-8ca0-5821d2ae24c9.png">

But since this is done in firebase, we don't have that much going on in here. So we can simplify this like the first image

**Comment by dinurymomshad** [comment]
We can also throw a local widget directory in there, if needed.

<img width="471" alt="Screenshot 2022-08-05 at 11 32 27 PM" src="https://user-images.githubusercontent.com/26508767/183130468-a6269734-513d-44c9-b786-0b0e7befc52d.png">

**Comment by KalleHallden** [comment]
Great suggestion and thank you for writing out the structure so thoroughly!

**Comment by dinurymomshad** [comment]
@KalleHallden do you want me to convert a feature like this? I think Login, Sign up would be a great point to start. Let me know if you want that.

Also, if we start working on this, then until this gets merged we should not accept any other changes in the authentication area to avoid merge conflict. Given this would be a huge change. LMK, what you think

**Comment by vancegillies** [comment]
This is by far the biggest issue with the codebase and should be nailed down before continuing. Especially because you have open sourced this, You want anyone jumping in to understand the codebase and how it is to be structured. 

I would recommend just making a new folder and start transferring stuff across, the app is small enough that it wouldn't take to long and it avoids all the merge conflicts. Once the new folder is in the desired state you can just point the 'main.dart' at the new folder

Another suggestion I have but can wait until after this change is complete is to move the app to the root of the repo.

**Comment by dinurymomshad** [comment]
@KalleHallden Expecting your feedback. If you agree I'll get started

**Comment by KalleHallden** [comment]
Yeah definitely man! Go for it, seems like you have a better idea of creating proper structure than me so that would be awesome!

**Comment by KalleHallden** [comment]
I believe this would be fine to work on in the master branch

**Comment by dinurymomshad** [comment]
@KalleHallden I have been wondering if we should stick with Bloc or change to something else? For example Riverpod may be? Let me know what you think. If you have any preferences or not.

**Comment by Scount** [comment]
@dinurymomshad As i can see, we aren't using the real bloc atm. I think it's more like an repository approach since the networking calls are directly inside the 'bloc'. 
I would prefere to use Riverpod, since we can also provide own states with the StateNotifierProvider or simply can use AsyncData or something like that. 
### Architecture change suggestion
Also i would make a change in the architecture. I can't see any folder for logic, therefore i would suggest to create a 'domain' and inside a 'logic' folder where all the logic can stay. It forces the developer to seperate logic from ui. 
Further more i would like to split the models into entity and model. 
- The entity is inside the domain folder. It is a class without any `fromJson` or t`oJson` stuff. 
- The model is inside data folder. It extends the entity and has all needed parsing methods like `fromJson` and t`oJson`.

**Example:**
<img width="124" alt="architecture" src="https://user-images.githubusercontent.com/13836859/184297492-2385f6e6-e4fc-47e2-aded-93570a7b43a4.png">

**Comment by dinurymomshad** [comment]
@Scount https://github.com/KalleHallden/exer_log/issues/10#issuecomment-1206686825
What do think about this?

**Comment by Scount** [comment]
Yes you are right with the view --> controller including logic --> repository. 
What i mean with logic is global logic, functions like sort and filter which are used multiple times from different controllers. I didn't dive in the code that deep to search for things like that but i think, if something like this exists it has to be defined globally so any controller hat access to the same logic.

**Comment by dinurymomshad** [comment]
I think I will get started with very basic implementation. And then we can proceed from there. I am using Riverpod

**Comment by dinurymomshad** [comment]
Work In Progress: https://github.com/dinurymomshad/exer_log/tree/feature/authentication-refactor

@KalleHallden can you assign this issue to me please? And also update in project board if you have any?

**Comment by suzanpradhan** [comment]
@dinurymomshad I suggest you to change the project folder to root too. (Currently its in app/exerlog/) Since this is already a massive update might as well add that too. 

And, @KalleHallden, lets merge #55 pull request first than anything, then we can update other features and contribute base on this architecture.

**Comment by dinurymomshad** [comment]
> @dinurymomshad I suggest you to change the project folder to root too. (Currently its in app/exerlog/) Since this is already a massive update might as well add that too.

You are right. Gonna do that.

**Comment by dinurymomshad** [comment]
@suzanpradhan done. Please give it a review if you will. I have built the project and ran the app.
