### ISSUE TITLE
Error, while creating a new workout in debug-mode

### ISSUE THREAD

**Issue by MhouneyLH** [KalleHallden/exer_log#132]
I want to contribute to this project and followed the "how to get started"-instructions described in the readme-file. Im still getting this error in heroes.dart, when i. e. creating a new workout in debug-mode. When trying the same thing without debug-mode than it works perfectly. 

![image](https://user-images.githubusercontent.com/78447003/185798755-7a9bc049-5ed1-4e61-80f1-8dfbfc2288fe.png)

Does anyone know how to deal with that or had the same problem?

**Comment by jorre127** [comment]
Yeah it's because the floating action button used in the cards needs a unique heroKey, but right now this isn't supplied. A solution would be to give them all unique keys, but personally I would just make the floating action button custom, because it's a really easy widget to make and would give us more customisation in the future.

**Comment by MhouneyLH** [comment]
Okay, so then could I work on this feature? I make a custom floating action button.
The custom floating action button should not have the heroTag-property, shouldn't it? (but all the other features + extra features for the future, when needed)

**Comment by jorre127** [comment]
@MhouneyLH  I don't have the right to assign you to this but I'd say go for it. Yeah the button shouldn't have a herotag seeing as we won't be using it. Things to note tho when making a custom FAB. Don't forget the inkwell effect a FAB has and don't forget the shadow. The rest should just be straightforward a round container with an icon in the middle and a color.

**Comment by jorre127** [comment]
@MhouneyLH If you would like to add extra features, I would change the inkwell animation to something else on IOS, because generally IOS doesn't have the inkwell effect.

**Comment by ramsy0dev** [comment]
we can set the heroTag for them to be ```null``` for now and then work on costumising them in the future. so that the issue be gone for now, and work on finding other issues. i guess

**Comment by jorre127** [comment]
@0RaMsY0  Don't think that is gonna work because they are all null right now. I think it uses a default key then, but seeing as they all use this default key the error occurs. Seeing as this isn't a breaking issue but just a error you get in the console, I believe we can take the time to fix it properly.

**Comment by ramsy0dev** [comment]
i have faced the same issue a couple of minutes ago i changed the heroTag for the floatingActionBar that save the workout into null, that means as you said they use the same heroTag so if when i changed one to null it worked
