### ISSUE TITLE
Ensure all contributors are added

### ISSUE THREAD

**Issue by tenshiAMD** [KalleHallden/exer_log#199]
For us to be greatly motivated, we need to ensure all contributors are added.

**Comment by tenshiAMD** [comment]
Currently, we have 11 out of 21. That's 10 contributors are still missing.

**Comment by mfederowicz** [comment]
@tenshiAMD i checked content of .all-contributorsrc and it contains only 11 login entries

**Comment by mfederowicz** [comment]
so I think we should add another PR (or comments in this issue) with commands for allcontributors[bot] to add another contributors, because content of https://github.com/EXERLOG/exer_log/graphs/contributors is generated automatically and can have much more contributors than .all-contributorsrc file which depends on bot commands :)
